# Generated by Django 2.2 on 2020-04-30 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_listing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Listing',
        ),
    ]
