# Generated by Django 2.2 on 2020-06-03 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_delete_listing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
